config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "blog_posts#index"


  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  # patch "blog_posts/:id/", to: "blog_posts#update"
  # note{
  # # in patch we no asssign the variable so that the rails is smart enough to understand the meaning shared by show variable 
  # }
  # delete "blog_posts/:id/", to: "blog_posts#destroy"

  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts
  # note{
  # # blog_post_path -> "/blog_posts/1"  (current path or adderss)
  # # blog_post_url  -> "http://localhost:3000/blog_posts/1" (entire domain or full address)
  # }
  resources :blog_posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    validates :title, presence: :true    
    validates :body, presence: :true
    
    scope :sorted,-> { order(published_at: :desc, updated_at: :desc)}    
    scope :draft,-> { where(published_at: nill)}    
    scope :published,-> { where("published_at: <= ?", Time.current)}    
    scope :scheduled,-> {whrer("published_at: > ?", Time.current)}

    def draft?
        published_at.nil?
      end
      
    def published?
        published_at? && published_at <= Time.current
    end
    def schedule?
        published_at? && published_at > Time.current
    end

end
 #  2       #BlogPost.all
            # BlogPost.draft
            # BlogPost.published
            # BlogPost.scheduled

            # `published_at` datetime field
            # - nil
            # - 1.year.alongside
            # - 1.year.from_now

#   1         # `Status` string field
#             # - draft 
#             # - published
#             # - scheduled

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
  # :registerable add i above line if you want new registration or new accouunt means no sign_up -
  # -request 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show] #when you have authenticate user method in device file bcuz you delete that
    before_action :set_blog_post,except: [:index, :new, :create] #only [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    def index
        # @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published_at
        @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.order(published_at: :desc)

    end

    def show
        # @blog_posts = BlogPost.published.find(params)
    end

    def new
        @blog_post = BlogPost.new
    end

    def create
        @blog_post = BlogPost.new(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
     #
    end

    def update
        #
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
       #
        @blog_post.destroy
        redirect_to root_path
    end

    private

    def blog_post_params
        params.require(:blog_post).permit(:title,:body, :published_at)
    end

    def set_blog_post
        # Use a ternary operator to conditionally find the BlogPost based on whether the user is signed in.
        @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
        
        # If the record is not found, rescue the ActiveRecord::RecordNotFound exception and redirect to the root path.
        rescue ActiveRecord::RecordNotFound
        redirect_to root_path
      end
      
end
    # when we added devices gem its alredy had several method just like below one to save time  this methods knows as helper methods
    # def authenticate_user!
    #     redirect_to new_user_session_path, alert: "You must sign in or sign up to continue." unless user_signed_in?
    # end


# note{
#     we added the device gem for security perpouse or many thing
#     even we need to access data by login account 
#     bt in incognimode of chrome we seen data without login just simple past url in incognito tab
#     like local_host:3000/1/edit so edit data without sign_in

#      so to overcome this thing we need to use index 1st line of code so we lock
# }

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<div class="form">
  <%= form_with model: blog_post do |form|%>
    <% if form.object.errors.any? %>
      <div class="errorShow">
        <% form.object.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    <% end %>
    <div class="username">
      <%= form.label :title%>
      <%= form.text_field :title%>
    </div>
    <div class="password">
      <%= form.label :body%>
      <%= form.text_area :body%>
    </div>
    <div class="password">
      <%= form.label :published_at %>
      <%= form.datetime_select :published_at, include_blank: true %>
    </div>
    <%= form.button%>
  <% end %>
</div>
<%# its not the full html code/form its just a partial or portion of the page %>

app/views/blog_posts/edit.html.erb
<h2>Edit Blog post</h2>
<%= render partial: "form", locals: {blog_post: @blog_post}%>
<%# in the above line we added blog_pst variable assign value and 
this value added in form partial file in form erb as a variable for access %>
<%# local variable assig instant arriable %>
<%= button_to "Delete",@blog_post, method: :delete, data: {turbo_confirm: "Are you sure ?"} %>
<%# {turbo_confirm: "Are you sure ?"} javascript method for rails 7 and higher this is hotwire 
turbo liberay  , %>
<%# the @blog_post must nessacery so its identify which elemet or a record want to delete  %>
<%# link_to only to make A GET REQUEAT only  %>
<%# in html we see which type of http request we sending which assign value of value tag in html (value:"patch"") %>

app/views/blog_posts/index.html.erb
<h1>My Blog</h1>
<% @blog_posts.each do |blog_post|%>
  <div>
    <% if blog_post.draft? %>
      <div class="p-2 rounded text-gray-900 bg-gray-100 prose">Draft</div>
    <% else blog_post.schedule?%>
      <div class="p-2 rounded text-gray-900 bg-blue-100 prose">schedule..</div>
    <% end %>
    <h3><%= link_to blog_post.title, blog_post %></h3>
    <%# <h3>= link_to blog_post.title,"/blog_posts_path{blog_post.id}"</h3> %>
    <%#= blog_post.body%>
  </div>
<% end %>
<%# blogPost id: 1  %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>
<%= render partial: "form", locals: {blog_post: @blog_post}%>
<%# in the above line we added blog_pst variable assign value and 
this value added in form partial file in form erb as a variable for access %>
<%# local variable assig instant %>

app/views/blog_posts/show.html.erb
<h3>Blog Info</h3>
<p class="mx-auto"><strong>Title</strong> <%= @blog_post.title %></p>
<p><strong>Body</strong> <%= @blog_post.body %></p>
<%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%#= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <%# #know tailwind is add in our appso its cancel our custom css  %>
  <%# so to used tailwind and our custome css we used to write a css property in body  %>
  <body class="prose mx-auto">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div>
      <% if user_signed_in? %>
        <%= link_to "New blog post", new_blog_post_path%>
        <%#= link_to "Profile", edit_user_registration_path %>
        <%= button_to "Log out", destroy_user_session_path , method: :delete%>
        <%# else %>
        <%#= link_to "Login", new_user_session_path%>
        <%#= link_to "Sign in", new_user_registration_path %>
      <% end %>
    </div>
    <div class="mx-auto">
      <%= yield %>
    </div>
  </body>
</html>